version: '3.0'
services:
  api:
    build: api
    links:
      - dashboard:dashboard
      - logger:logger
      - todo:todo
  dashboard:
    build: dashboard
    links:
      - logger:logger
      - todo:todo
  logger:
    build: logger
  todo:
    build: todo
    links:
      - logger:logger
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
