version: '3.0'
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    links:
      - dashboard:dashboard
      - logger:logger
      - todo:todo
  dashboard:
    build: ./dashboard
    links:
      - logger:logger
      - todo:todo
  logger:
    build: ./logger
    links:
      - redis:redis
  todo:
    build: ./todo
    links:
      - logger:logger
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
